- site/zh-cn/g2/3.x/api/chart.md
> doc(api): Correct spelling and supplement.

- bin/screenshot.js
- site-config.js
- site/zh-cn/g2/3.x/demo/other/rain-and-flow.html
> Daily 20171208

- site/zh-cn/g2/3.x/demo/map/bubble-map.html
- site/zh-cn/vis/chart/bubble-map.md
- site/zh-cn/vis/chart/dot-map.md
> doc: map review.

- site/zh-cn/g2/3.x/demo/bar/basic.html
> fix: demo.

- site/zh-cn/f2/3.x/demo/line/line-hybrid.html
chore(demo): provide demo for hybrid-line-chart.
提供了一个实线/虚线混合的折线图的demo
> chore(demo) : provide demo for hybrid-line-chart

- README.md
- bin/server.js
1. add some guides in readme.
2. now `--open` will open homepage instead of static resource at '/'.
---
略微减少了萌新（比如我）的上手难度，run dev --open 打开的是网站的首页，不再是静态资源页面
> chore(readme) : update readme and change open parameter effection.

- site/zh-cn/g2/3.x/demo/map/drill-down.html
- theme/default/src/demos.js
- theme/default/src/home.js
* demos 页面切换主题后，点击可以把主题设置带到详细页面了
* 地图下钻的 bug 已修复
* 样式的 bug
* 等等
> Daily 20171222

- site/zh-cn/g2/3.x/api/chart.md
- site/zh-cn/g2/3.x/demo/other/doubal-axis.html
- [x ] `npm test` passes
- [x ] tests and/or benchmarks are included
- [ x] commit message follows commit guidelines
* 添加 padding  的 API
* 添加 双轴的 demo
> feat(demo): add double axis demo, add padding api

- site/zh-cn/g2/3.x/api/chart.md
- site/zh-cn/g2/3.x/demo/bar/waterfall.html
- site/zh-cn/g2/3.x/demo/other/bullet-graph.html
- site/zh-cn/g2/3.x/demo/other/doubal-axis.html
* 自定义图例时直接让用户配置 marker 的所有的配置项，而不是使用简单的字符串。
> change custom legend marker

- site/zh-cn/g2/3.x/api/chart.md
> doc:fix `chart.arc`'s `top` param

- site-config.js
- site/zh-cn/f2/3.x/api/chart.md
- site/zh-cn/g2/3.x/api/chart.md
> feat(f2): update f2 cdn and api

- site/zh-cn/f2/3.x/demo/bar/animated-column.html
- site/zh-cn/f2/3.x/demo/line/dash.html
- site/zh-cn/f2/3.x/demo/pie/ring.html
- site/zh-cn/f2/3.x/demo/radar/area.html
> fix ill demos

- site/zh-cn/f2/3.x/index.md
- site/zh-cn/g6/1.x/index.md
> typo error

- theme/default/assets/image/icon/gallery.svg
> fix typo in filename

- site/zh-cn/g2/3.x/api/geom.md
- site/zh-cn/g2/3.x/demo/pie/donut.html
> add geom api

- site/zh-cn/g2/3.x/api/chart.md
-  [x] `npm test` passes
-  [x] tests and/or benchmarks are included
-  [x] commit message follows commit guidelines
API 文档错误
> fix api doc

- theme/default/templates/layout.html
> fix(site): add suffix to each page title

- site/zh-cn/g2/3.x/api/chart.md
tooltip.containerTpl 的默认值更新为和实际相符
> docs: tooltip.containerTpl默认值更新

- site/zh-cn/g2/3.x/api/scale.md
> docs: 补充漏了的 sync 属性

- site/zh-cn/gallery/g2/pie-column.html
- site/zh-cn/gallery/g2/pie-size.html
- site/zh-cn/gallery/g2/pie-slice.html
* 添加几个饼图的demo , 饼图-柱状图、饼图中间分隔、饼图半径增加映射
> add pie demos to gallery

- site/zh-cn/g2/3.x/demo/funnel/basic.html
- site/zh-cn/g2/3.x/tutorial/customize-shape.md
- site/zh-cn/gallery/g2/pie-platelets.html
- site/zh-cn/gallery/g2/pie-triangle.html
> add pie demos

- site/zh-cn/g2/3.x/api/chart.md
- site/zh-cn/g2/3.x/api/scale.md
- site/zh-cn/g2/3.x/tutorial/attr.md
- site/zh-cn/g2/3.x/tutorial/axes.md
https://github.com/antvis/g2/issues/531
> fix(doc): fixing demo links

- site/zh-cn/vis/blog/f2-3.1.1-releasing.md
> replace image

- site/zh-cn/g2/3.x/demo/gauge/basic.html
- site/zh-cn/g2/3.x/demo/gauge/color.html
- site/zh-cn/g2/3.x/demo/gauge/text.html
* 修复一下仪表盘指针对不齐的问题
* 指针的颜色跟仪表盘一致
> fix(demo): fixed bug of gauge demo

- lib/compile-inline-scripts.js
- site-config.js
- site/zh-cn/f2/3.x/demo/pie/ring.html
- site/zh-cn/g2/3.x/api/chart.md
- site/zh-cn/g2/3.x/demo/map/bubble-map.html
- site/zh-cn/g2/3.x/tutorial/guide.md
- site/zh-cn/g2/3.x/tutorial/tooltip.md
* 增加guide-regionFilter相关documents
* fix g2-domo-map-bubble-map bug
> add guide-regionFilter documents

- site-config.js
- site/zh-cn/f2/3.x/api/canvas.md
- site/zh-cn/f2/3.x/api/legend.md
- site/zh-cn/f2/3.x/api/util.md
- site/zh-cn/f2/3.x/demo/line/legend-single-select.html
> f2 3.1.8 publish

- site/zh-cn/g2/3.x/tutorial/load-data.md
> feat(doc): update doc

- site/zh-cn/f2/3.x/api/chart.md
- site/zh-cn/f2/3.x/demo/guide/regionFilter.html
> Rich f2 demos

- site/zh-cn/g2/3.x/api/animate.md
- site/zh-cn/g2/3.x/tutorial/theme.md
> Daily 0620

- site/zh-cn/g2/3.x/api/chart.md
fix chart api `getXY` doc example
> doc: fix chart api getXY doc example

- site/zh-cn/f2/3.x/demo/line/gold.html
> feat: add new f2 demo

- site/zh-cn/f2/3.x/demo/line/gold.html
> fix: fix fontSize value error

- site-config.js
- site/zh-cn/f2/3.x/api/tooltip.md
- site/zh-cn/f2/3.x/demo/bar/dodge-column-with-label.html
- site/zh-cn/f2/3.x/demo/bar/negative-column-1.html
- site/zh-cn/f2/3.x/demo/other/clock-in.html
- site/zh-cn/f2/3.x/tutorial/history.md
> publish 3.1.14

- site-config.js
- site/zh-cn/f2/3.x/api/chart.md
- site/zh-cn/f2/3.x/api/guide.md
- site/zh-cn/f2/3.x/api/interaction.md
- site/zh-cn/f2/3.x/demo/axis/iconfont.html
- site/zh-cn/f2/3.x/demo/guide/iconfont.html
- site/zh-cn/f2/3.x/demo/guide/regionFilter.html
- site/zh-cn/f2/3.x/demo/health/fitness-ring.html
- site/zh-cn/f2/3.x/demo/health/heart-rate.html
- site/zh-cn/f2/3.x/demo/interaction/interval-select.html
- site/zh-cn/f2/3.x/demo/interaction/pie-select.html
- site/zh-cn/f2/3.x/demo/interaction/steps-pan.html
- site/zh-cn/f2/3.x/demo/interaction/timecat-pinch-pan.html
- site/zh-cn/f2/3.x/demo/interaction/x-pan.html
- site/zh-cn/f2/3.x/demo/interaction/x-pinch-pan.html
- site/zh-cn/f2/3.x/demo/interaction/xy-pinch-pan.html
- site/zh-cn/f2/3.x/demo/pie/pie-with-iconfont-and-label.html
- site/zh-cn/f2/3.x/demo/pie/pie-with-iconfont.html
- site/zh-cn/f2/3.x/demo/pie/pie-with-label.html
- site/zh-cn/f2/3.x/tutorial/update.md
> Daily 0713 f2

- site/zh-cn/g2/3.x/demo/area/with-negative.html
- site/zh-cn/g2/3.x/demo/bar/basic.html
- site/zh-cn/g2/3.x/demo/bar/grouped-column.html
- site/zh-cn/g2/3.x/demo/bar/grouped.html
- site/zh-cn/g2/3.x/demo/bar/stacked-column.html
- site/zh-cn/g2/3.x/demo/bar/stacked-percentage-column.html
- site/zh-cn/g2/3.x/demo/bar/stacked.html
- site/zh-cn/g2/3.x/demo/line/curved.html
- site/zh-cn/g2/3.x/demo/line/series.html
- site/zh-cn/g2/3.x/demo/line/step-series.html
- site/zh-cn/g2/3.x/demo/pie/donut.html
- site/zh-cn/g2/3.x/demo/pie/innerlabel.html
- site/zh-cn/g2/3.x/demo/pie/labelline.html
- site/zh-cn/g2/3.x/demo/pie/multi-level.html
- site/zh-cn/g2/3.x/demo/point/scatter-series.html
- site/zh-cn/g2/3.x/demo/point/scatter-shapes.html
> remove dataset fold

- site/zh-cn/g2/3.x/demo/relation/polar-treemap.html
- site/zh-cn/g2/3.x/demo/relation/treemap-children.html
- site/zh-cn/g2/3.x/demo/relation/treemap.html
> doc(g2):add children treemap

- site/zh-cn/g2/3.x/api/chart.md
- site/zh-cn/g2/3.x/demo/component/region-filter-guide1.html
> 3.3，更新 guide 文档

- site/zh-cn/g2/3.x/api/tooltip.md
> tooltip-documents

- site/zh-cn/g2/3.x/api/geom.md
> chore(geom): update document of label

- site/zh-cn/g2/3.x/demo/component/label-scatter.html
- site/zh-cn/g2/3.x/demo/component/region-filter-guide1.html
> remove unuseful code.

- site/zh-cn/g2/3.x/demo/component/data-marker-data-region.html
> demo style check.

- site/zh-cn/g2/3.x/tutorial/theme.md
> docs: fix deprecated Global config

- site/zh-cn/g2/3.x/demo/other/column-marked.html
Use new api when `registerShape`.
> fix(demo): use new API when registerShape

- site/zh-cn/f2/3.x/index.md
- site/zh-cn/g2/3.x/index.md
- site/zh-cn/l7/1.x/index.md
- theme/default/src/home.less
> product homepage style adjust.

- site/zh-cn/g2/3.x/api/chart.md
> [doc] fix a wrong example of coord transform

- site/zh-cn/l7/1.x/index.md
* fix: video 标签使用 cover 的 object-fit
before: 妹子的比例都变形了。。
after:
> fix: use cover fit instead of fill

- site/zh-cn/g2/3.x/demo/line/line11.html
Closes https://github.com/antvis/g2/issues/1129
> Closes https://github.com/antvis/g2/issues/1129

- site/zh-cn/g2/3.x/demo/column/stacked-column.html
- theme/default/src/demo.js
> fix(demo): add cat to stacked column chart

- site/zh-cn/g6/3.x/index.md
> fix(g6): fix g6 homepage demo

- site/zh-cn/g6/3.x/demo/flow/er-diagram.html
- site/zh-cn/g6/3.x/demo/tree/tree-compact-box.html
- site/zh-cn/g6/3.x/demo/tree/tree-dendrogram.html
- site/zh-cn/g6/3.x/demo/tree/tree-mindmap.html
- site/zh-cn/g6/3.x/index.md
> Daily 190422

- site-config.js
- site/zh-cn/g6/3.x/demo/tree/radial-tree.html
- site/zh-cn/g6/3.x/demo/tree/tree-compact-box.html
- site/zh-cn/g6/3.x/demo/tree/tree-dendrogram.html
- site/zh-cn/g6/3.x/demo/tree/tree-mindmap.html
- theme/default/assets/data/algorithm-category.json
> Daily 190423

- theme/default/src/Home/home.index.less
- theme/default/src/common.less
- theme/default/src/demo.js
- theme/default/src/demo.less
- theme/default/src/drawer.less
- theme/default/templates/demo.html
> fix style bugs on mobile

- site/zh-cn/g6/3.x/demo/tree/cloudatlas-tree.html
- site/zh-cn/l7/1.x/demo/mapmarker/circle.html
> fix(demo): data source

- site-config.js
- site/zh-cn/data.js
- site/zh-cn/g6/3.x/data.js
- site/zh-cn/g6/3.x/demo/flow/node-flow.html
- site/zh-cn/g6/3.x/demo/interaction/toggle-node-img.html
- site/zh-cn/g6/3.x/demo/shape/cardNode.html
- site/zh-cn/g6/3.x/demo/shape/pieNode.html
- site/zh-cn/g6/3.x/demo/text/text-ellipse.html
- site/zh-cn/g6/3.x/demo/text/text-wrap.html
- site/zh-cn/g6/3.x/demo/tree/cloudatlas-tree.html
- site/zh-cn/g6/3.x/demo/tree/custom-tree.html
- site/zh-cn/g6/3.x/demo/tree/radial-tree.html
- site/zh-cn/g6/3.x/demo/tree/tree-compact-box.html
- site/zh-cn/g6/3.x/demo/tree/tree-dendrogram.html
- site/zh-cn/g6/3.x/demo/tree/tree-edge-label.html
- site/zh-cn/g6/3.x/demo/tree/tree-indented.html
- site/zh-cn/g6/3.x/demo/tree/tree-mindmap.html
- theme/default/templates/layout.html
> add G6 demos

- site/zh-cn/g6/3.x/demo/interaction/dynamic-data.html
- site/zh-cn/g6/3.x/demo/shape/listNode.html
- site/zh-cn/g6/3.x/demo/shape/polyline.html
- site/zh-cn/g6/3.x/demo/shape/register-polyline.html
> add register shape demo

- theme/default/templates/partial/footer.html
- theme/default/templates/partial/header.html
旧版网站改为 https://antvis.github.io/old-site ，仓库迁移到 https://github.com/antvis/old-site
https://github.com/antvis/antvis.github.io 这个仓库将征用为新版网站的开发仓库。
> docs: change old site url

- theme/default/src/demos.js
- theme/default/templates/demos.html
> fix: fix the header and left menu in demos page of all the products

- site/zh-cn/g6/3.x/demo/net/arc-diagram.html
- site/zh-cn/g6/3.x/demo/net/base-force.html
- site/zh-cn/g6/3.x/demo/net/interactive-force.html
> fix: g6 force demo use inner layout

- theme/default/src/Home/VideoBanner.jsx
> fix: lark link to new label page

- theme/default/templates/layout.html
> adjust redirect js exec time

- site/g2/doc/index.html
- site/g6/doc/index.html
- site/vis/doc/index.html
> fix: 修复文档链接跳转不精准的问题
